### ISSUE TITLE
Add a `WavReader` method for seeking to the start of the audio data?

### ISSUE THREAD

**Issue by mitchmindtree** [ruuda/hound#18]
I'm currently attempting to implement an Iterator that cycles over a WAV file using `WavReader` in a personal project and something along these lines would be super helpful.

I can imagine a more general seeking implementation might also be useful for users who want to jump to a certain location within a file (e.g. a user clicks the timeline within a music player application). Rather than seeking in bytes as the `Seek` trait does, I picture this API would allow for seeking in samples (where `0` would be the first sample and `wav_reader.len()` would be the end).

I'm going to have a go at implementing this now but thought I'd post an issue in case you are around to share your thoughts sooner :)

**Comment by ruuda** [comment]
Yes, this is something that has been on my to-do list for a long time. Thanks for taking this up!
