### ISSUE TITLE
Move to the RustAudio org?

### ISSUE THREAD

**Issue by erlend-sh** [ruuda/hound#24]
Might you consider moving hound and claxon to the [RustAudio](https://github.com/RustAudio) organisation?

- Lowers the bus factor a teensy bit
- Gives the RustAudio collective more authority and visibility
- Easier for newcomers to find solid audio libraries in one place.

**Comment by mitchmindtree** [comment]
Just for the record I think @ruuda is doing a great job with hound currently and don't see a great need for it to be moved. That said, they are more than welcome to if they wish - I think @ruuda is already an admin there!

**Comment by ruuda** [comment]
Thank you for taking the time to open an issue. I have been thinking about the bus factor lately, and what I think would be more helpful is to invite a few others as owners on crates.io. I don’t feel a need to move the repository.

> Just for the record I think @ruuda is doing a great job with hound

Thanks!

**Comment by erlend-sh** [comment]
No words, greatly appreciate the work you’re all doing for the Rust audio story! 👏
