### ISSUE TITLE
Panic on malformed input

### ISSUE THREAD

**Issue by Shnatsel** [ruuda/hound#26]
I have copy-pasted the decode_full.rs target and run it under AFL with 6 different wav files with various settings generated with Audacity. It has immediately discovered a panic: `thread 'main' panicked at 'Not in the data chunk.', libcore/option.rs:960:5`

Tested on commit 0db81279f11117dfa21c9ee6b531c5dad37c9221

The offending file is attached, gzipped so that github would accept the upload: [hound_not_in_data_chunk.wav.gz](https://github.com/ruuda/hound/files/2372301/hound_not_in_data_chunk.wav.gz)

Steps to reproduce:
```bash
git clone https://github.com/Shnatsel/hound-afl
cd hound-afl
cargo build
target/debug/hound-afl < /path/to/offending/file
```

I wonder why this panic was not discovered before. All I've done is copy-pasting an existing fuzz target and running it.

**Comment by ruuda** [comment]
You are using the `master` branch to which #25 was just merged, it’s not in a releasable state. Can you reproduce under v3.4.0?

**Comment by Shnatsel** [comment]
No, I cannot reproduce this panic on 3.4.0

**Comment by ruuda** [comment]
I’ll consider it closed then.
