### ISSUE TITLE
Incorrectly read wav-file with 1 channel and 8 bits per sample

### ISSUE THREAD

**Issue by Amomum** [ruuda/hound#52]
I'm trying to read a wav file with this spec: `WavSpec { channels: 1, sample_rate: 8000, bits_per_sample: 8, sample_format: Int }` - one channel, 8 bits per sample, so each sample should fit in u8.

I read it like this (which very well may be incorrect since I'm not very good in Rust):

``` rust
    let samples: Vec<u8> = wavreader.samples()
        .map(|s: Result<i32, hound::Error>| s.unwrap() as u8)
        .collect();
```

and then I print it:

``` rust
    for i in (0..samples.len()).step_by(11) {
        for j in 0..11 {
            print!("0x{:02x}, ", samples[i+j]);
        }
        println!();
    }
```

Here's a piece from the beginning of the file:

<details> <summary> samples </summary>

```
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xfe, 
0xff, 0xff, 0x00, 0x01, 0x00, 0x01, 0x00, 0xff, 0xff, 0x01, 0x01, 
0x00, 0xff, 0xfe, 0xff, 0x00, 0xff, 0xff, 0xff, 0xfe, 0xfe, 0xfe, 
0xfe, 0xfe, 0xff, 0xfe, 0xfd, 0xfd, 0xfe, 0xfe, 0xfe, 0xfd, 0xfd, 
0xfc, 0xfd, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfc, 0xfd, 0xfd, 
0xfe, 0xff, 0x00, 0x01, 0x02, 0x03, 0x03, 0x04, 0x06, 0x07, 0x08, 
```

</details>

This, however, is not equal to what I see in hex editor (since every sample is 8 bit and there's only 1 channel, every byte should be equal to one sample, right?):

<details> <summary> hex editor </summary>

![](https://user-images.githubusercontent.com/4990494/112693168-37a69c00-8e91-11eb-8dd3-6acc4f03fbb0.png)

</details>

<details> <summary>Here's side-by-side comparison, differences are highlighted:</summary>

![](https://user-images.githubusercontent.com/4990494/112693460-bb608880-8e91-11eb-99be-0b2d45585971.png)

</details>

Looks like most significant bit of every byte is inverted o_o

Can you please tell me what am I doing wrong? Here's the troublesome file - https://gofile.io/d/s8GPnc

**Comment by ruuda** [comment]
> Looks like most significant bit of every byte is inverted o_o

This is working as intended: for a bit depth of 8 bits per sample, the wav format stores *unsigned* samples, but for other bit depths, it stores *signed* samples. Hound always returns signed samples, so hide this quirk in the format, it subtracts 128 for you.

**Comment by Amomum** [comment]
Oh.. that is kinda surprising for me. Correct me if I'm wrong but I can't see any mention of this behaviour in [docs for WavReader](https://docs.rs/hound/3.4.0/hound/struct.WavReader.html).

**Comment by ruuda** [comment]
It is not documented in Hound itself, because it is an internal quirk of the wave format, it’s not something that callers need to be concerned with. Callers always work with signed samples, and signed types are the only types that implement the `Sample` trait.

If you are interested in the format details, check out page 59 of [the RIFF spec](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/riffmci.pdf).

**Comment by Amomum** [comment]
Okay, fair enough. If it is intended behaviour than there is no real issue here and this can be closed. 
I was surprised because I never seen that behaviour before (for instance, [wav crate](https://docs.rs/wav/0.6.0/wav/) doesn't do that).
