### ISSUE TITLE
Feature request: `Sample::as_f32`

### ISSUE THREAD

**Issue by vihdzp** [ruuda/hound#65]
I am making a library for audio creation and want to add support for (floating point) audio buffers from WAV files. In order to make this work, I would need the ability to convert an arbitrary sample into a floating point value.

This wouldn't be a direct cast, but rather an appropriate rescaling. For instance, 
```rust
fn as_f32(x: i8) -> f32 {
    x as f32 / i8::MAX as f32
}
```
or perhaps something slightly more clever that clamps the range between `-1.0` and `1.0` exactly.

The reason I'm making this an issue rather than a direct PR is that this might create some confusion with the (unused?) `Sample::as_i16`. That one is a direct cast, rather than a conversion, and it would be odd having different behavior for these two methods. Maybe `into_f32` could be a better name?

**Comment by ruuda** [comment]
This also came up here: https://github.com/ruuda/hound/issues/57#issuecomment-1214424166. My conclusion is that there is no way to implement this that is both obvious and consistent across all types, so I would like to leave it out of Hound; you can normalize the samples wherever you consume them. It’s slightly more code, but at least the behavior is explicit.

**Comment by vihdzp** [comment]
Alright, that's understandable. Thank you!
