### ISSUE TITLE
Proposal to rebase #58 onto 3.5.0 for a new release

### ISSUE THREAD

**Issue by maxwellmckinnon** [ruuda/hound#66]
Hi Ruud,

Just putting an item here to remind myself to cherry pick @spacecams's great change #58  (e284521fffa505a8316114a04cec0a8a23232ada) on
top of v3.5.0 for a new release to crates.io

Thanks a lot for supporting this release,
Max

**Comment by ruuda** [comment]
This is done, and I published version 3.5.1 to crates.io. Thanks again!
