### ISSUE TITLE
Use the `byteorder` crate for little endian manipulation

### ISSUE THREAD

**Issue by julienw** [ruuda/hound#7]
Hi,

I thought you could use https://crates.io/crates/byteorder to read/write your PCM as it seems to implement basically the same things as you do.

**Comment by ruuda** [comment]
Thank you for the suggestion. When I first wrote this code, reading integers was supported by the standard library. Unfortunately it was removed, so I wrote my own, and the byteorder crate appeared around the same time. It’s only a few lines, and I don’t think removing those justifies adding dependency. I consider not having dependencies a feature. Also, byteorder doesn’t deal with 24-bit integers. So at this time I don’t think it is worth switching.
