### ISSUE TITLE
[Beginner] How to change duration of sound in file?

### ISSUE THREAD

**Issue by raleighlittles** [ruuda/hound#71]
I'm obviously very unfamiliar with Wave files and audio writing. In the example, how do you control/change the duration of each sound generated?

I saw your example of generating a 440 Hz sine wave, but how do you specify how long you want that sound to last? (Do Wave files even have a "duration"?)

For my project I need to play tones for an arbitrary length. For example, a 440 Hz sound for 5 milliseconds, followed by a 500 Hz sound for 10 milliseconds, etc.

**Comment by ruuda** [comment]
The duration of a file in seconds is $\frac{n}{cr}$ where $n$ is the number of samples, $c$ is the number of channels, and $r$ is the sample rate in Hertz.
